// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdzIUtI9JZNusNyn7kwsJ-gmw1d-GkyYU',
    appId: '1:427454952936:android:9170c35f4d224ef38ba05d',
    messagingSenderId: '427454952936',
    projectId: 'mpakodem',
    storageBucket: 'mpakodem.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDISRrYxRlTXdKkwn19PIT5bc7ctyTpLk',
    appId: '1:427454952936:ios:fdfbca37f82570eb8ba05d',
    messagingSenderId: '427454952936',
    projectId: 'mpakodem',
    storageBucket: 'mpakodem.firebasestorage.app',
    iosClientId: '427454952936-dd8dctq4gqom6s4k1itra68jbuas90vb.apps.googleusercontent.com',
    iosBundleId: 'com.example.course',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdZKeLRBdeKyfDwW6-l5OG_oezPekS9lk',
    appId: '1:427454952936:web:f9a6e3c2dfce75dc8ba05d',
    messagingSenderId: '427454952936',
    projectId: 'mpakodem',
    authDomain: 'mpakodem.firebaseapp.com',
    storageBucket: 'mpakodem.firebasestorage.app',
    measurementId: 'G-R4KX1Q2S2B',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdZKeLRBdeKyfDwW6-l5OG_oezPekS9lk',
    appId: '1:427454952936:web:21b3ae844268867a8ba05d',
    messagingSenderId: '427454952936',
    projectId: 'mpakodem',
    authDomain: 'mpakodem.firebaseapp.com',
    storageBucket: 'mpakodem.firebasestorage.app',
    measurementId: 'G-1WV4QTNRW0',
  );

}